# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RxSwift01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift01
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'RxSwift01Tests' do
    #inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'RxSwift01UITests' do
    #inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

end
